<?php
class EBXWCTS_TimeValues {
    public static $wcts_time_values = [
        'NOT SET',
        '7:00 AM',
        '7:15 AM',
        '7:30 AM',
        '7:45 AM',
        '8:00 AM',
        '8:15 AM',
        '8:30 AM',
        '8:45 AM',
        '9:00 AM',
        '9:15 AM',
        '9:30 AM',
        '9:45 AM',
        '10:00 AM',
        '10:15 AM',
        '10:30 AM',
        '10:45 AM',
        '11:00 AM',
        '11:15 AM',
        '11:30 AM',
        '11:45 AM',
        '12:00 PM',
        '12:15 PM',
        '12:30 PM',
        '12:45 PM',
        '1:00 PM',
        '1:15 PM',
        '1:30 PM',
        '1:45 PM',
        '2:00 PM',
        '2:15 PM',
        '2:30 PM',
        '2:45 PM',
        '3:00 PM',
        '3:15 PM',
        '3:30 PM',
        '3:45 PM',
        '4:00 PM',
        '4:15 PM',
        '4:30 PM',
        '4:45 PM',
        '5:00 PM',
        '5:15 PM',
        '5:30 PM',
        '5:45 PM',
        '6:00 PM',
        '6:15 PM',
        '6:30 PM',
        '6:45 PM',
        '7:00 PM',
        '7:15 PM',
        '7:30 PM',
        '7:45 PM',
        '8:00 PM',
        '8:15 PM',
        '8:30 PM',
        '8:45 PM',
        '9:00 PM',
        '9:15 PM',
        '9:30 PM',
        '9:45 PM',
        '10:00 PM',
        '10:15 PM',
        '10:30 PM',
        '10:45 PM',
        '11:00 PM',
        '11:15 PM',
        '11:30 PM',
        '11:45 PM',
        '12:00 AM',
        '12:15 AM',
        '12:30 AM',
        '12:45 AM',
        '1:00 AM',
        '1:15 AM',
        '1:30 AM',
        '1:45 AM',
        '2:00 AM',
        '2:15 AM',
        '2:30 AM',
        '2:45 AM',
        '3:00 AM',
        '3:15 AM',
        '3:30 AM',
        '3:45 AM',
        '4:00 AM',
        '4:15 AM',
        '4:30 AM',
        '4:45 AM',
        '5:00 AM',
        '5:15 AM',
        '5:30 AM',
        '5:45 AM',
        '6:00 AM',
        '6:15 AM',
        '6:30 AM',
        '6:45 AM'
    ];
    public static $timezones = [
        'Midway Island (GMT-11:00)' => 'Pacific/Midway',
        'Samoa (GMT-11:00)' => 'Pacific/Samoa',
        'Hawaii (GMT-10:00)' => 'Pacific/Honolulu',
        'Alaska (GMT-09:00)' => 'US/Alaska',
        'Pacific Time (US & Canada) (GMT-08:00)' => 'America/Los_Angeles',
        'Arizona (GMT-07:00)' => 'America/Tijuana',
        'Mountain Time (US & Canada) (GMT-07:00)' => 'US/Mountain',
        'Mexico City (GMT-06:00)' => 'America/Mexico_City',
        'Saskatchewan (GMT-06:00)' => 'Canada/Saskatchewan',
        'Central America (GMT-06:00)' => 'America/Managua',
        'Central Time (US & Canada) (GMT-06:00)' => 'US/Central',
        'Eastern Time (US & Canada) (GMT-05:00)' => 'US/Eastern',
        'Bogota (GMT-05:00)' => 'America/Bogota',
        'Caracas (GMT-04:30)' => 'America/Caracas',
        'Atlantic Time (Canada) (GMT-04:00)' => 'Canada/Atlantic',
        'La Paz (GMT-04:00)' => 'America/La_Paz',
        'Newfoundland (GMT-03:30)' => 'Canada/Newfoundland',
        'Buenos Aires (GMT-03:00)' => 'America/Argentina/Buenos_Aires',
        'Greenland (GMT-03:00)'=> 'America/Godthab',
        'Mid Atlantic (GMT-02:00)' => 'America/Noronha' ,
        'Azores (GMT-01:00)' => 'Atlantic/Azores',
        'Cape Verde Is. (GMT-01:00)' => 'Atlantic/Cape_Verde',
        'Casablanca (GMT)' => 'Africa/Casablanca',
        'Greenwich Mean Time (GMT)' => 'Etc/Greenwich',
        'Dublin (GMT)' => 'Etc/Greenwich',
        'Lisbon (GMT)' => 'Europe/Lisbon',
        'London (GMT)' => 'Europe/London',
        'Monrovia (GMT)' => 'Africa/Monrovia',
        'Amsterdam (GMT+01:00)' => 'Europe/Amsterdam',
        'Belgrade (GMT+01:00)'=> 'Europe/Belgrade',
        'Berlin (GMT+01:00)' => 'Europe/Berlin',
        'Bratislava (GMT+01:00)' => 'Europe/Bratislava',
        'Brussels (GMT+01:00)' => 'Europe/Brussels',
        'Budapest (GMT+01:00)' => 'Europe/Budapest',
        'Copenhagen (GMT+01:00)' => 'Europe/Copenhagen',
        'Ljubljana (GMT+01:00)'  => 'Europe/Ljubljana',
        'Madrid (GMT+01:00)' => 'Europe/Madrid',
        'Paris (GMT+01:00)' => 'Europe/Paris',
        'Prague (GMT+01:00)' => 'Europe/Prague',
        'Rome (GMT+01:00)'=> 'Europe/Rome',
        'Sarajevo (GMT+01:00)' => 'Europe/Sarajevo',
        'Skopje (GMT+01:00)' => 'Europe/Skopje',
        'Stockholm (GMT+01:00)' => 'Europe/Stockholm',
        'Vienna (GMT+01:00)'=> 'Europe/Vienna',
        'Warsaw (GMT+01:00)' => 'Europe/Warsaw',
        'Zagreb (GMT+01:00)' => 'Europe/Zagreb',
        'Athens (GMT+02:00)' => 'Europe/Athens',
        'Bucharest (GMT+02:00)' => 'Europe/Bucharest',
        'Cairo (GMT+02:00)'=> 'Africa/Cairo',
        'Harare (GMT+02:00)' => 'Africa/Harare',
        'Helsinki (GMT+02:00)' => 'Europe/Helsinki',
        'Istanbul (GMT+02:00)'  => 'Europe/Istanbul',
        'Jerusalem (GMT+02:00)' => 'Asia/Jerusalem',
        'Kyiv (GMT+02:00)' => 'Europe/Helsinki',
        'Riga (GMT+02:00)' => 'Europe/Riga',
        'Sofia (GMT+02:00)' => 'Europe/Sofia',
        'Tallinn (GMT+02:00)' => 'Europe/Tallinn',
        'Vilnius (GMT+02:00)' => 'Europe/Vilnius',
        'Baghdad (GMT+03:00)' => 'Asia/Baghdad',
        'Kuwait (GMT+03:00)'=> 'Asia/Kuwait',
        'Nairobi (GMT+03:00)' => 'Africa/Nairobi',
        'Riyadh (GMT+03:00)' => 'Asia/Riyadh',
        'Tehran (GMT+03:30)' => 'Asia/Tehran',
        'Moscow (GMT+04:00)' => 'Europe/Moscow',
        'St. Petersburg (GMT+04:00)' => 'Europe/Moscow',
        'Baku (GMT+04:00)' => 'Asia/Baku',
        'Muscat (GMT+04:00)' => 'Asia/Muscat',
        'Tbilisi (GMT+04:00)' => 'Asia/Tbilisi',
        'Yerevan (GMT+04:00)'=> 'Asia/Yerevan',
        'Kabul (GMT+04:30)' => 'Asia/Kabul',
        'Karachi (GMT+05:00)' => 'Asia/Karachi',
        'Tashkent (GMT+05:00)' => 'Asia/Tashkent',
        'Kolkata (GMT+05:30)' => 'Asia/Kolkata',
        'Kathmandu (GMT+05:45)' => 'Asia/Katmandu',
        'Ekaterinburg (GMT+06:00)' => 'Asia/Yekaterinburg',
        'Almaty (GMT+06:00)' => 'Asia/Almaty',
        'Dhaka (GMT+06:00)' => 'Asia/Dhaka',
        'Novosibirsk (GMT+07:00)' => 'Asia/Novosibirsk',
        'Bangkok (GMT+07:00)' => 'Asia/Bangkok',
        'Jakarta (GMT+07:00)' => 'Asia/Jakarta',
        'Krasnoyarsk (GMT+08:00)' => 'Asia/Krasnoyarsk',
        'Chongqing (GMT+08:00)' => 'Asia/Chongqing',
        'Hong Kong (GMT+08:00)' => 'Asia/Hong_Kong',
        'Kuala Lumpur (GMT+08:00)' => 'Asia/Kuala_Lumpur',
        'Perth (GMT+08:00)' => 'Australia/Perth',
        'Singapore (GMT+08:00)' => 'Asia/Singapore',
        'Taipei (GMT+08:00)' => 'Asia/Taipei',
        'Ulaan Bataar (GMT+08:00)' => 'Asia/Ulan_Bator',
        'Urumqi (GMT+08:00)' => 'Asia/Urumqi',
        'Irkutsk (GMT+09:00)' => 'Asia/Irkutsk',
        'Seoul (GMT+09:00)' => 'Asia/Seoul',
        'Tokyo (GMT+09:00)' => 'Asia/Tokyo',
        'Adelaide (GMT+09:30)'=> 'Australia/Adelaide',
        'Darwin (GMT+09:30)' => 'Australia/Darwin',
        'Yakutsk (GMT+10:00)' => 'Asia/Yakutsk',
        'Brisbane (GMT+10:00)' => 'Australia/Brisbane',
        'Canberra (GMT+10:00)' => 'Australia/Canberra',
        'Guam (GMT+10:00)' => 'Pacific/Guam',
        'Hobart (GMT+10:00)' => 'Australia/Hobart',
        'Melbourne (GMT+10:00)' => 'Australia/Melbourne',
        'Port Moresby (GMT+10:00)' => 'Pacific/Port_Moresby',
        'Sydney (GMT+10:00)' => 'Australia/Sydney',
        'Vladivostok (GMT+11:00)' => 'Asia/Vladivostok',
        'Magadan (GMT+12:00)' => 'Asia/Magadan',
        'Auckland (GMT+12:00)' => 'Asia/Vladivostok', 
        'Fiji (GMT+12:00)' => 'Pacific/Fiji'
    ];
}